import { searchWikidata } from "./wikidata.js";

const json=(data,status=200,origin="*")=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"public, max-age=300, s-maxage=900","access-control-allow-origin":origin,"access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"content-type"}});
const corsOrigin=(request,env)=>{const allowed=(env.ALLOWED_ORIGINS||env.ALLOWED_ORIGIN||"*").split(",").map(x=>x.trim()).filter(Boolean);const origin=request.headers.get("origin")||"";return allowed.includes("*")?"*":allowed.includes(origin)?origin:null};
const tmdb=async(path,env,params={})=>{if(!env.TMDB_READ_TOKEN)throw Error("TMDB_READ_TOKEN is not configured");const u=new URL("https://api.themoviedb.org/3"+path);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,String(v))});const r=await fetch(u,{headers:{accept:"application/json",authorization:"Bearer "+env.TMDB_READ_TOKEN}});if(!r.ok)throw Error("TMDB request failed: "+r.status);return r.json()};
const image=p=>p?"https://image.tmdb.org/t/p/w500"+p:"";
const normalizeTmdb=m=>({id:"tmdb:"+m.id,title:m.title||m.original_title||"",originalTitle:m.original_title||"",year:m.release_date?m.release_date.slice(0,4):"",release:m.release_date||"",lang:m.original_language||"",genre:Array.isArray(m.genres)?m.genres.map(x=>x.name).join(" · "):"",overview:m.overview||"",poster:m.poster_path?image(m.poster_path):"",backdrop:m.backdrop_path?image(m.backdrop_path):"",rating:Number(m.vote_average||0),votes:Number(m.vote_count||0),director:"",cast:[],source:"TMDB",sourceUrl:"https://www.themoviedb.org/movie/"+m.id});
const providers={wikidata:searchWikidata,tmdb:async(q,e)=>{const d=await tmdb("/search/movie",e,{query:q,include_adult:"false",language:"en-US",region:"IN",page:"1"});return(d.results||[]).filter(x=>x&&(x.title||x.original_title)).slice(0,10).map(normalizeTmdb)}};
export default{async fetch(request,env){const origin=corsOrigin(request,env);if(!origin)return json({error:"Origin not allowed"},403,"*");if(request.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":origin,"access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"content-type"}});try{const u=new URL(request.url),route=u.pathname.replace(/\/+$/,"")||"/";if(route==="/health")return json({ok:true,service:"BoxOffice India movie API",provider:env.SEARCH_PROVIDER||"wikidata"},200,origin);if(route!=="/search"&&route!=="/api/search")return json({error:"Not found"},404,origin);const q=String(u.searchParams.get("q")||"").trim();if(q.length<2||q.length>120)return json({results:[],query:q},200,origin);const providerName=env.SEARCH_PROVIDER||"wikidata",provider=providers[providerName];if(!provider)return json({error:"Provider not configured"},500,origin);if(providerName==="tmdb"&&!env.TMDB_READ_TOKEN)return json({error:"TMDB_READ_TOKEN is not configured"},500,origin);const results=await provider(q,env);return json({results,query:q,count:results.length,source:providerName},200,origin)}catch(error){return json({error:error.message||"Movie service unavailable"},502,origin)}}};
