// Wikidata movie provider for BoxOffice India
const API="https://www.wikidata.org/w/api.php";
const FILM_CLASSES=new Set(["Q11424","Q24869","Q202866","Q20650540","Q24862","Q93204"]);
async function wd(params,env){const u=new URL(API);for(const[k,v]of Object.entries({format:"json",formatversion:"2",...params}))u.searchParams.set(k,v);const r=await fetch(u,{headers:{"User-Agent":"BoxOfficeIndia/1.0 ("+(env.CONTACT_URL||"https://sumitkumarsharma11x-glitch.github.io/boxoffice-india/")+")","Accept":"application/json","Accept-Encoding":"gzip, deflate"}});if(!r.ok)throw Error("wikidata_"+r.status);return r.json()}
const ids=(e,p)=>(e.claims?.[p]||[]).map(c=>c.mainsnak?.datavalue?.value?.id).filter(Boolean);
const val=(e,p)=>e.claims?.[p]?.[0]?.mainsnak?.datavalue?.value;
const label=e=>e?.labels?.en?.value||e?.labels?.hi?.value||Object.values(e?.labels||{})[0]?.value||"";
const year=e=>{const a=(e.claims?.P577||[]).map(c=>c.mainsnak?.datavalue?.value?.time).filter(Boolean).map(t=>parseInt(t.slice(1,5),10)).filter(Number.isFinite);return a.length?Math.min(...a):null};
const chunks=(a,n)=>{const o=[];for(let i=0;i<a.length;i+=n)o.push(a.slice(i,i+n));return o};
export async function searchWikidata(query,env){const langs=(env.SEARCH_LANGS||"en,hi").split(",").map(x=>x.trim()).filter(Boolean);const sr=await Promise.all(langs.map(l=>wd({action:"wbsearchentities",search:query,language:l,uselang:l,type:"item",limit:"20"},env).then(x=>x.search||[]).catch(()=>[])));const qids=[];for(const list of sr)for(const x of list)if(!qids.includes(x.id))qids.push(x.id);if(!qids.length)return[];const es=await Promise.all(chunks(qids.slice(0,40),50).map(c=>wd({action:"wbgetentities",ids:c.join("|"),props:"claims|labels|descriptions",languages:"en|hi"},env)));const all=Object.assign({},...es.map(x=>x.entities||{}));const films=qids.map(id=>all[id]).filter(e=>e&&ids(e,"P31").some(x=>FILM_CLASSES.has(x))).slice(0,10);if(!films.length)return[];const refs=new Set();for(const f of films){ids(f,"P57").slice(0,2).forEach(x=>refs.add(x));ids(f,"P161").slice(0,4).forEach(x=>refs.add(x));ids(f,"P364").slice(0,1).forEach(x=>refs.add(x))}const rs=await Promise.all(chunks([...refs],50).map(c=>wd({action:"wbgetentities",ids:c.join("|"),props:"labels",languages:"en|hi"},env).catch(()=>({entities:{}}))));const labels=Object.assign({},...rs.map(x=>x.entities||{}));const name=id=>label(labels[id]);return films.map(f=>({id:"wd:"+f.id,wikidataId:f.id,title:label(f),originalTitle:val(f,"P1476")?.text||"",year:year(f),description:f.descriptions?.en?.value||f.descriptions?.hi?.value||"",overview:"",posterUrl:null,rating:null,language:name(ids(f,"P364")[0])||null,director:ids(f,"P57").slice(0,2).map(name).filter(Boolean),cast:ids(f,"P161").slice(0,4).map(name).filter(Boolean),imdbId:val(f,"P345")||null,source:"wikidata",sourceUrl:"https://www.wikidata.org/wiki/"+f.id}))}
